### ISSUE TITLE
✨타임매니저에 임의로 DT배율 조정기능 추가(배율 0이면 정지)

### ISSUE THREAD

**Issue by oljindudol** [Remnants-of-Remnants/DirectX3D#11]
디버그 랑 컨탠츠에 효과가 좋을것으로 기대함

**Comment by superozing** [comment]
1. 타임 매니저에 DT 세팅 시 배율 값 적용
2. 타임 매니저에 DT 세팅 시 DT 활성화 여부 적용
3. 전역 함수 생성
4. 타임 관리 스크립트 생성 후 
5. 스크립트 파람 세팅
6. 더미 오브젝트 생성 후 부착

SCRIPT_PARAM이 개선되면 추가적으로 버튼으로 함수를 호출하거나,
DT같은 정보를 read only로 보게 하도록 개선할 수 있겠어요.

**Comment by superozing** [comment]
임시 레벨에 추가까지 완료. 나중에 추가적인 기능이 있다면 새로 이슈를 파는게 좋아보여요
