### ISSUE TITLE
♻️♻️코드 제네레이터수정 + 스트링 테이블화

### ISSUE THREAD

**Issue by oljindudol** [Remnants-of-Remnants/DirectX3D#15]
스크립트
스테이트
매크로 기능 추가
엑셉리스트 제거
## 스크립트 매니저 생성
  - [x] 파일 처음부터 다시쓰기 옵션 추가
  - [x] 헤더 생성
  - [x] cpp 생성

## 매크로 헤더 생성
- [x] fx
- [x] 텍스쳐
- [x] 머터리얼
- [x] 프리팹
- [x] 애니메이션
- [x] 사운드

**Comment by oljindudol** [comment]
패스
 fx
 텍스쳐
![Image](https://github.com/Remnants-of-Remnants/DirectX3D/assets/82567430/de12c4e4-6f03-4846-8f28-1e3330e3178e)



에셋키
 쉐이더
 머터리얼
 매쉬
 프리펩
 텍스쳐
 애니메이션

쉐이더코드 함수이름

**Comment by jeontigger** [comment]
![Image](https://github.com/Remnants-of-Remnants/DirectX3D/assets/20323844/173d553a-e458-4c1f-91e7-3c694c8a2717)
