### ISSUE TITLE
✨Param UI 콜백버튼 만들기

### ISSUE THREAD

**Issue by oljindudol** [Remnants-of-Remnants/DirectX3D#88]

**Comment by superozing** [comment]
```cpp
typedef  void(*BtnCallBack)(void);
typedef  void(CEntity::* DelegateFunc)(void);
```
이걸로 멤버 변수 처럼 

![Image](https://github.com/Remnants-of-Remnants/DirectX3D/assets/127123002/9ba1c567-c75c-470c-9d80-85adab0f3b18)

이렇게 넣어줄 수 있어

**Comment by superozing** [comment]
![Image](https://github.com/Remnants-of-Remnants/DirectX3D/assets/127123002/f538021e-5dc8-454d-a075-94aa8ed3d2f7)

함수 호출은 이런 식으로 할 수 있어

```cpp
	// CallBack
	if (m_CallBackFunc != nullptr) 
		m_CallBackFunc();
	
	// Delegate
	if (m_Inst != nullptr && m_Delegate != nullptr)
		(m_Inst->*m_Delegate)();
```

**Comment by superozing** [comment]
![Image](https://github.com/Remnants-of-Remnants/DirectX3D/assets/127123002/2dc3d89e-e83a-4206-81fc-feab454b45ab)

```cpp
m_UI->SetDeletage((CEntity*)this, (DelegateFunc)&CDiceScript::DiceClickedDelegateFunc);

```

**Comment by superozing** [comment]
@zkzkzkzkzkzz
